name: multistep
channels:
  - defaults
dependencies:
  - pip
  - numpy=1.16.4
  - pyspark
  - requests
  - click
  - numpy
  - pip:
    - tensorflow==1.13.1
    - keras==2.2.4
    - mlflow>=1.0
    - boto3
